#+TITLE: Setting Up Development Environment
#+DESCRIPTION: Building Emacs from source with OpenSUSE.

* openSUSE

** Installing multimedia codecs

openSUSE doesn’t include proprietary and patented software by default. Many codecs required to decode and play some common and popular multimedia formats, hence aren’t available, and those multimedia files can’t be played. A third party repository, called Packman, provides these missing codecs for openSUSE.

#+begin_src shell
sudo zypper ar -cfp 90 https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/Essentials packman-essentials
sudo zypper refresh
sudo zypper dup --from packman-essentials --allow-vendor-change
sudo zypper install ffmpeg libavcodec-full vlc-codecs pipewire-aptx gstreamer-plugins-bad-codecs gstreamer-plugins-ugly-codecs gstreamer-plugins-libav gstreamer-plugins-good gstreamer-plugins-good-extra gstreamer-plugins-bad gstreamer-plugins-ugly
#+end_src


* Emacs

** Building from source

As per a Reddit post, it is an option to build Emacs from a ~git worktree~. That way, I can experiment with different builds, different configuration options, etc. This avoids polluting the main Emacs directory, and git won't complain about unsaved changes I pull to update the sources.

*** Adding and Installing Dependency Packages

#+begin_src shell
sudo zypper si -d emacs
#+end_src

This command installs only build dependencies of ~Emacs~ (the specified package). ~si~ is short-hand for ~source-install~ and ~-d~ flag is for ~--build-deps-only~.

** Installing from a package

#+begin_src shell
sudo zypper install emacs
#+end_src
